flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- extensible-exceptions-0.1.1.4
- hostname-1.0
- old-locale-1.0.0.7
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- xml-1.3.14
resolver: ghc-8.0.1
